ktor:
  application:
    modules:
      - hr.algebra.perf.ApplicationKt.module
  deployment:
    port: 8080
database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/postgres"
  username: perf_a
  password: 1234567890
  driverClassName: "org.postgresql.Driver"
  schema: "perf"
  embedded: false
  hikari:
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 300000
    connectionTimeout: 20000
    maxLifetime: 1800000
    poolName: "KtorPerfPool"
    autoCommit: true
    connectionTestQuery: "SELECT 1"
redis:
  host: "localhost"
  port: 6379
  ttl: 300

kafka:
  brokers: "localhost:9092"
  topic: "order-events"
  acks: "1"
