ktor:
  application:
    modules:
      - hr.algebra.perf.ApplicationKt.module
  deployment:
    port: 8080
database:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: perf_a
  password: 1234567890
  driver: "org.postgresql.Driver"
  schema: "perf"
  embedded: false
redis:
  host: "localhost"
  port: 6379
  ttl: 300

kafka:
  brokers: "localhost:9092"
  topic: "order-events"
  acks: "1"
